spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
  profiles:
    active: "@spring.profiles.active@"

hazelcast:
  declaration-map:
    init: false
    size: 1_000_000

logging.level:
  ru.parma.ventslavovich.hazelcast: debug